"""initial_public_schema

Revision ID: 12fa4d624308
Revises: 
Create Date: 2025-06-20 16:20:35.096518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '12fa4d624308'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_permissions_id'), 'permissions', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_permissions_name'), 'permissions', ['name'], unique=False, schema='public')
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_roles_id'), 'roles', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_roles_name'), 'roles', ['name'], unique=False, schema='public')
    op.create_table('tenant_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_tenant_permissions_id'), 'tenant_permissions', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_tenant_permissions_name'), 'tenant_permissions', ['name'], unique=True, schema='public')
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('schema_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('subdomain', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('billing_tier', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdomain'),
    schema='public'
    )
    op.create_index(op.f('ix_public_tenants_id'), 'tenants', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_tenants_schema_name'), 'tenants', ['schema_name'], unique=False, schema='public')
    op.create_table('users',
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='public'
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expiration_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id'),
    sa.UniqueConstraint('refresh_token'),
    schema='public'
    )
    op.create_index(op.f('ix_public_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False, schema='public')
    op.create_table('token_blocklist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('jti', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_token_blocklist_id'), 'token_blocklist', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_token_blocklist_jti'), 'token_blocklist', ['jti'], unique=False, schema='public')
    op.create_index(op.f('ix_public_token_blocklist_tenant'), 'token_blocklist', ['tenant'], unique=False, schema='public')
    op.create_table('user_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['public.roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'role_id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_user_roles_id'), 'user_roles', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_user_roles_id'), table_name='user_roles', schema='public')
    op.drop_table('user_roles', schema='public')
    op.drop_index(op.f('ix_public_token_blocklist_tenant'), table_name='token_blocklist', schema='public')
    op.drop_index(op.f('ix_public_token_blocklist_jti'), table_name='token_blocklist', schema='public')
    op.drop_index(op.f('ix_public_token_blocklist_id'), table_name='token_blocklist', schema='public')
    op.drop_table('token_blocklist', schema='public')
    op.drop_index(op.f('ix_public_refresh_tokens_id'), table_name='refresh_tokens', schema='public')
    op.drop_table('refresh_tokens', schema='public')
    op.drop_table('users', schema='public')
    op.drop_index(op.f('ix_public_tenants_schema_name'), table_name='tenants', schema='public')
    op.drop_index(op.f('ix_public_tenants_id'), table_name='tenants', schema='public')
    op.drop_table('tenants', schema='public')
    op.drop_index(op.f('ix_public_tenant_permissions_name'), table_name='tenant_permissions', schema='public')
    op.drop_index(op.f('ix_public_tenant_permissions_id'), table_name='tenant_permissions', schema='public')
    op.drop_table('tenant_permissions', schema='public')
    op.drop_index(op.f('ix_public_roles_name'), table_name='roles', schema='public')
    op.drop_index(op.f('ix_public_roles_id'), table_name='roles', schema='public')
    op.drop_table('roles', schema='public')
    op.drop_index(op.f('ix_public_permissions_name'), table_name='permissions', schema='public')
    op.drop_index(op.f('ix_public_permissions_id'), table_name='permissions', schema='public')
    op.drop_table('permissions', schema='public')
    # ### end Alembic commands ###
